blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # Post views
    # path('', views.PostListView.as_view(), name='post_list'),
    path('', views.index, name='index'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list_by_tag, name='post_list_by_tag'),
    path('search/', views.post_search, name='post_search'),
]

blogger/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog import views


from blog.sitemaps import PostSitemap
sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', views.index, name='index')
    
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self)\
                    .get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                             choices=STATUS_CHOICES,
                             default='draft')
    objects = models.Manager() #the default manager
    published = PublishedManager() # Our custom manager
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[self.publish.year,
                              self.publish.month,
                              self.publish.day, self.slug])

    class Meta:
        ordering = ('-publish',)
    def __str__(self):
        return self.title
# Create your models here.

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class searchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage,\
    PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, searchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector,\
    SearchQuery, SearchRank

"""class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'"""

def index(request):
    posts = Post.published.all()
    recents = posts.order_by('-publish')[:5]
    return render(request, 'index.html', {'posts': recents}) 

def post_list_by_tag(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is not an integer, deliver the first page
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {
        'page': page,
        'posts': posts,
        'tag': tag
    })


def post_share(request, post_id):
    # Retrieve post by Id
    sent = False
    post = get_object_or_404(Post, id=post_id, status='published')
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields Valid
            cleaned_data = form.cleaned_data
            # Send Email
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cleaned_data['name']} Recommends you read "\
                f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cleaned_data['name']} \'s comments: {cleaned_data['comments']}"

            send_mail(subject, message, 'yeku.wilfred@yahoo.com',
                      [cleaned_data['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    #List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A new comment was added
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    # List of similar Posts

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-publish')[:4]
    print(post)
    return render(request, 'blog/post/detail.html',
                  {
                      'post': post,
                      'comments': comments,
                      'new_comment': new_comment,
                      'comment_form': comment_form,
                      'similar_posts': similar_posts
                  }
                  )


def post_search(request):
    form = searchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = searchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + \
                SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.3).order_by('-rank')
    return render(request,
                  'blog/post/search.html',
                  {
                   'form': form,
                   'query': query,
                   'resuts': results
                  })

blog/templates/IND.html
{% extends "base.html" %}
{% load blog_tags %}
{% block title %} Blog | Yeku Wilfred C.{% endblock %}
{% block content %}
<section class="wow fadeIn parallax" data-stellar-background-ratio="0.5" style="background-image:url('http://placehold.it/1920x1100');">
    <div class="container-fluid padding-five-lr">
        <div class="row">                  
            <div class="col-lg-5 col-md-5 col-sm-12 pull-right">
                <div class="padding-ten-all sm-padding-70px-all xs-padding-25px-all bg-white box-shadow-light">
                    <i class="fa fa-quote-left text-deep-pink icon-large margin-15px-bottom"></i>
                    <h5 class="text-extra-dark-gray margin-50px-bottom sm-margin-20px-bottom alt-font">
                        Hello, I am a Full-Stack Developer from Douala, Cameroon.
                        I hold a Bachelor's Degree of Software Engineering from University Institute of Technology Douala.
                    </h5>
                    <ul class="text-medium list-style-3">
                        <li><span class="width-30 display-inline-block">Name:</span>Yeku Wilfred Chetat</li>
                        <li><span class="width-30 display-inline-block">Github:</span><a href="https://github.com/chetat" target="_blank">@Chetat</a></li>
                        <li><span class="width-30 display-inline-block">LinkedIn:</span><a href="https://linkedin.com/yeku-wilfred-chetat" target="_blank">Yeku Wilfred Chetat</a></li>
                        <li>
                            <span class="width-30 display-inline-block">Upwork:</span> <a href="https://www.upwork.com/o/profiles/users/~011884062ea2574991/" target="_blank">Yeku W.</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="wow fadeIn">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 wow fadeIn">
                <div class="position-relative icon-with-paragraph">
                    <span class="text-deep-pink position-absolute left-0 top-0 alt-font special-char-extra-large sm-display-none">*</span> 
                    <h6 class="font-weight-300 text-extra-dark-gray width-90 padding-nineteen-left md-padding-twenty-left md-width-100 sm-no-padding-left xs-margin-five-bottom">
                        You have in mind to build an outstanding, robust, organized, and well-structured Web application and/or APIs that will increase your business value? Look further no more, I am here to help you create value for your business and organization.</h6>
                </div>
            </div>
            <div class="col-lg-6 col-md-5 col-md-offset-1 col-lg-offset-0 col-sm-6 col-xs-12 wow fadeIn last-paragraph-no-margin" data-wow-delay="0.2s">
                <p class="text-medium font-weight-300 width-70 line-height-26 md-width-100">
                    Passionate and self-motivated full-stack developer with a mindset of customer satisfaction and getting things done with minimum delay. 
I have 3 years of experience building web applications and APIs using Flask. I have a broad knowledge of the following technologies: 
Cloud services for deployment: Heroku / AWS
Server deployment and containerization tools: Kubernetes / Docker.
Database ORM and ODM: SQLAlchemy, MongoEngine
M
                    </p>
                <a href="#expertise" class="inner-link text-uppercase alt-font margin-15px-top display-inline-block font-weight-600 text-deep-pink text-extra-small">Check My Expertise <i class="fas fa-long-arrow-alt-right margin-5px-left text-medium position-relative top-2" aria-hidden="true"></i></a>
            </div>
        </div>
    </div>
</section>
 <!-- start blog section -->
 <section id="blog" class="bg-light-gray wow fadeIn">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center margin-100px-bottom sm-margin-70px-bottom xs-margin-50px-bottom">
                <h5 class="text-uppercase alt-font text-extra-dark-gray margin-20px-bottom font-weight-700 sm-width-100 xs-width-100">Recent Blog Posts</h5>
                <span class="separator-line-horrizontal-medium-light2 bg-deep-pink display-table margin-auto width-100px"></span>
            </div> 
        </div>
        <div class="row equalize xs-equalize-auto">
            <!-- start blog post item -->
           {% for post in posts %}
                <div class="col-md-4 col-sm-4 col-xs-12 xs-margin-ten-bottom wow fadeInUp blog-post-style5 last-paragraph-no-margin">
                    <div class="blog-post bg-white">
                        <div class="blog-post-images overflow-hidden">
                            <a href="javascript:void(0);">
                                <img src="http://placehold.it/900x650" alt="">
                            </a>
                            <div class="blog-categories bg-white text-uppercase text-extra-small alt-font"><a href="{{ post.get_absolute_url }}"> 
                                {% for tag in post.tags.all %}
                               
                                    {{ tag.name }}
                                
                                {% if not forloop.last %}, {% endif %}
                            {% endfor %}
                            
                            </a></div>
                        </div>
                        <div class="post-details inner-match-height padding-ten-all xs-padding-five-lr">
                            <div class="blog-hover-color"></div>
                            <a href="javascript:void(0);" class="alt-font post-title text-medium text-extra-dark-gray width-90 display-block md-width-100 margin-5px-bottom">{{ post.title}}</a>
                            <div class="author">
                                <span class="text-medium-gray text-uppercase text-extra-small display-inline-block">by <a href="javascript:void(0);">{{post.author}}</a>&nbsp;&nbsp;|&nbsp;&nbsp;{{ post.publish }}</span>
                            </div>
                            <div class="separator-line-horrizontal-full bg-medium-gray margin-seven-tb md-margin-four-tb"></div>
                            <p>{{post.body}}</p>
                        </div>
                    </div>
                </div>
           {% endfor %}
            </ul>
        </div>
    </div>
</section>
<!-- end blog section -->
<section class="wow fadeIn parallax" id="services">

</section>
{% endblock%}

blog/templates/blog/post/det.html
{% extends "base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|markdown }}
  <p>
    <a href="{% url 'blog:post_share' post.id%}">
      Share Post
    </a>
  </p>
  {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} comment{{total_comments | pluralize }}
    </h2>
  {% endwith %}

  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks}}
    </div>
  {% empty %}
    <p>There are no comments yet</p>
  {% endfor %}
  {% if new_comment %}
     <h2> Your comment has been added </h2>
  {% else %}
     <form method="post">
       {{ comment_form.as_p }}
       {% csrf_token %}
       <p><input type="submit" value="Add Comment"></p>
     </form>
  {% endif %}
  <h2>Similar Posts</h2>
  {% for post in similar_posts %}
     <p>
       <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
     </p>
  {% empty %}
     There are no similar posts yet
  {% endfor %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list2.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %} My Blog {% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2> Posts tagged with "{{ tag.name }}"</h2>
    {% endif%}

   
    
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url}}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            Tags: {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
              {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>

        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30}}
    {% endfor %}
    {% include "pagination.html" with page=posts %}


{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      {{ post.body|markdown|truncatewords_html:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %} Share a Post {% endblock %}
{% block content %}

   {% if sent %}
        <h1>Email Sent Success</h1>
        <p>
            "{{post.title}}" was successfully sent to {{form.cleaned_data.to}}
        </p>
   {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{form.as_p}}
            {% csrf_token %}

            <input type="submit" value="Send E-mail">
        </form>
    {% endif %}
{% endblock %}

blog/templates/index.html
{% extends "base.html" %}
{% load blog_tags %}

{% block content %}
<!-- Page Content -->
<div class="container my-5">
    {% if tag %}
    <h2> Posts tagged with "{{ tag.name }}"</h2>
    {% endif%}
    <div class="row">


        <div class="col-md-8">


            {% for post in posts %}
            <!-- Blog Entries Column -->

            <!-- Blog Post -->
            <div class="card mb-4">
                <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                <div class="card-body">
                    <h2 class="card-title">{{post.title}}</h2>
                    <p class="card-text">{{ post.body|markdown|truncatewords_html:30}}</p>
                    <a href="{{ post.get_absolute_url}}" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                    Posted on {{ post.publish }} by
                    <a href="#">{{ post.author }}</a>
                    <p class="tags">
                        Tags: {% for tag in post.tags.all %}
                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                            {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                </div>
            </div>
            {% endfor %}
            <!-- Pagination -->
            <div class="text-center">
                {% include "pagination.html" with page=posts %}
            </div>
        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

            <!-- Search Widget -->
            <div class="card my-4">
                <h5 class="card-header">Search</h5>
                <div class="card-body">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-append">
                            <button class="btn btn-secondary" type="button">Go!</button>
                        </span>
                    </div>
                </div>
            </div>

            <!-- Categories Widget -->
            <div class="card my-4">
                <h5 class="card-header">Categories</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                <li>
                                    <a href="#">Web Design</a>
                                </li>
                                <li>
                                    <a href="#">HTML</a>
                                </li>
                                <li>
                                    <a href="#">Freebies</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                <li>
                                    <a href="#">JavaScript</a>
                                </li>
                                <li>
                                    <a href="#">CSS</a>
                                </li>
                                <li>
                                    <a href="#">Tutorials</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Side Widget -->
            <div class="card my-4">
                <h5 class="card-header">Side Widget</h5>
                <div class="card-body">
                    You can put anything you want inside of these side widgets. They are easy to use, and feature the
                    new Bootstrap 4 card containers!
                </div>
            </div>

        </div>
    </div>
    <!-- /.row -->


</div>
<!-- /.container -->
{% endblock %}

blog/templates/index2.html
{% extends "base.html" %}
{% load blog_tags %}
{% block title %} Blog | Yeku Wilfred C.{% endblock %}

{% block content %}
    {% if tag %}
        <h2> Posts tagged with "{{ tag.name }}"</h2>
    {% endif%}

   
    
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url}}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            Tags: {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
              {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>

        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30}}
    {% endfor %}
    {% include "pagination.html" with page=posts %}


{% endblock %}

blog/templates/pagination.html
<div class="pagitation">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">previous</a>
        {% endif %}

        <span class="current">
            Page {{page.number }} of {{ page.paginator.num_pages}}
        </span> 
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}"></a>
        {% endif %}
    </span>

</div>